name: golangci-lint
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5
        with:
          go-version: '1.22.x'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6