name: "Binary Build"

on:
  push:
    branches:
      - main

jobs:
  pre-release:
    name: "Binary Build"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Build & test"
        run: |
          make release-all

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            release/*
